### ISSUE TITLE
Unable to run certain rom hacks that work fine on lr-snes9x and lr-snes9x2005 .

### ISSUE THREAD

**Issue by MapleStoryPSN** [libretro/snes9x2010#121] opened 2018-10-01 09:12 UTC
Namely the Super Mario World 9th Annual Vanilla Level Design Contest, which can be found here: https://www.smwcentral.net/?p=section&a=details&id=14812

The game just hangs on a black screen upon launch.

**Comment by meepingsnesroms** [comment] 2018-10-02 21:54
Dupe of #89

**Closed by meepingsnesroms** 2018-10-02 21:54 UTC
