### ISSUE TITLE
possible ROM size issue

### ISSUE THREAD

**Issue by DuckSalmon** [libretro/snes9x2010#89] opened 2016-12-20 20:29 UTC
I have the Super mario world Central Vanilla design level contest 9 and my retroarch (on retropie) cannot run it, maybe because this ROM size is too big (6 MB)

actual can this emulator run ROM over 6MB?

**Comment by meepingsnesroms** [comment] 2016-12-20 21:56
If it doesn't have obscure special chips it should be able to run any SNES rom

**Comment by Alcaro** [comment] 2016-12-20 21:57
Does SA-1 count as obscure?

**Comment by meepingsnesroms** [comment] 2016-12-20 22:10
No I count superfx sa1 and the DSP series as regular add-on chips.

Obscure is like the super Gameboy and shogi arm chips.

**Comment by DuckSalmon** [comment] 2016-12-21 11:50
then why this rom cannot run on my retropie?
the windows version of snes9x run it perfectly

**Comment by fr500** [comment] 2016-12-21 15:13
Snes9x or snes9x2010?
Also bear in mind.... Different ABI different problems

**Comment by meepingsnesroms** [comment] 2016-12-21 17:08
Tested it on Android,fails on 2010 works on newest.

**Comment by hizzlekizzle** [comment] 2016-12-21 17:21
Looks to be a known issue from this era:
http://www.smwcentral.net/?p=viewthread&t=39663

**Comment by meepingsnesroms** [comment] 2016-12-21 17:27
Yeah also fails on 2005,2002 just SIGSEGV and exits.

**Comment by DuckSalmon** [comment] 2016-12-22 13:20
so, to use this game on retropie i must wait a future version of the emulator based on the newer libraries of snes9x ? well xD

**Comment by meepingsnesroms** [comment] 2016-12-22 15:03
Or use the newest snes9x.(without a date at the end)
What device do you run RetroPie on?(pi2 or 3 should be able to handle it)

**Comment by DuckSalmon** [comment] 2016-12-22 15:22
I have the Pi3 with the last version of retropie
I think that the default One is the lr-snes9x-next
Based on the 2010 version
Other lb emulators are armsnes, catsfc, pocketsnes

**Comment by meepingsnesroms** [comment] 2016-12-22 19:24
Do you know how to use root and compile?(If you do you could compile the newest libretro snes9x for pi3)

**Comment by fr500** [comment] 2016-12-22 19:28
retropie is not android...
Not sure what you mean with root

**Comment by meepingsnesroms** [comment] 2016-12-22 19:53
Compile for armv7 debian then put it in the RetroPie core directory.

**Comment by DuckSalmon** [comment] 2016-12-22 20:28
Sorry guys
I'm an old player but i' new with these things
I've edited something but never compiled an Image or an app
I'll try with an another emulator
Any advices for the choice?

**Comment by meepingsnesroms** [comment] 2016-12-22 22:11
If you want to keep RetroPie use apt or synaptic to install the newest standalone snes9x, otherwise just install lakka.(Use RetroArch as your OS then you should be able to install the newest RetroArch snes9x)
From the core names of RetroPie it's emulators seem way outdated anyway.

**Comment by deltabeard** [comment] 2020-04-20 13:47
Commit d8e5d090aa804463a3b27d65aaa657769d8b976d from Snes9x is required to fix this issue.
Commit c3ce28b49d84d451541459f65af38f11326136b5 from Snes9x is required to fix a segmentation that occurs when the fix is applied.

I've already applied the first commit to my fork. There's much work to be done on cherry-picking the second commit though. Once tested, I'll make a pull request.

**Comment by deltabeard** [comment] 2020-04-20 16:19
The issue is fixed in my fork. I'll make a pull request shortly.

**Comment by hizzlekizzle** [comment] 2020-04-20 22:23
should be fixed now with #130 so I'm going to close this. We'll reopen if not.

**Closed by hizzlekizzle** 2020-04-20 22:23 UTC
